### ISSUE TITLE
Ordering manual for popular manufacturers

### ISSUE THREAD

**Issue by spotlesscoder** [ijnekenamay/HAGIWOs_Module#6]
Hi,

thanks for sharing this :)
I want to make some modules and order the PCBs on JLCPCB. The have so many options during the order process that I am completely confused what I need to order.

Could you please make a list with the most important settings to make?

**Comment by ijnekenamay** [comment]
Hello. It would be better for you to look at the JLCPCB's help on this.
All I can say is that it is a 2-layer board.
Also, as a side note, there are many people who have published improved and better PCBs since my design. I am keeping this repository for learning the basic circuitry, but I would not recommend actually building one at this time.

**Comment by spotlesscoder** [comment]
Thanks for the quick reply :)

Could you maybe provide a link to the improved PCB you mentioned?

**Comment by ijnekenamay** [comment]
Here is my recommendation.
https://github.com/Testbild-synth
You can also search for “HAGIWO” on github for more variations.

**Comment by spotlesscoder** [comment]
Very nice, thank you :)
